services:
  mongo:
    image: "mongo:5.0.3-focal"
    ports:
      - "27017:27017"
    env_file:
      - ".env"
  web:
    build: .
    depends_on:
      - "mongo"
    command: node_modules/.bin/nodemon server.js --host=0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      # Bind mount of app source code
      - ".:/app"
      # Unnamed volume mount to prevent bind mount of 'node_modules'
      - /app/node_modules
