services:
  frontend:
    build: .
    command: node_modules/.bin/react-scripts start --host=0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      # Bind mount of app source code
      - "./client:/opt/app/frontend"
      # Unnamed volume mount to prevent bind mount of 'node_modules'
      - /opt/app/frontend/node_modules
