services:
  blog-engine:
    build: .
    command: node_modules/.bin/nodemon server.js --host=0.0.0.0
    ports:
      - '3000:3000'
    volumes:
      # Bind mount of app source code
      - '.:/app'
      # Unnamed volume mount to prevent bind mount of 'node_modules'
      - /app/node_modules
    env_file:
      - '.env'
