version: 2.1
jobs:
  build_test:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: docker build -t blog-engine .
workflows:
  build_and_test:
    jobs:
      - build_test
