version: 2.1
jobs:
  build_test:
    docker:
      - image: cimg/node:14.17.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Catch syntax errors and coding style
          command: npm run lint && npm run format -- --check
      - run:
          name: Run tests
          command: npm run test
workflows:
  build_and_test:
    jobs:
      - build_test
